###Get all uers
GET http://localhost:3003/users

###Get all products
GET http://localhost:3003/products/?name=moni
###Get all products
GET http://localhost:3003/products/search

### Delete product by id
DELETE http://localhost:3003/products/prod001

### Delete user by id
DELETE http://localhost:3003/users/u002

### Edit user by id
PUT http://localhost:3003/users/u001
Content-Type: application/json

{
    "id": "teste",
    "name": "newOwnerName",
    "email": "kasdhjof@gmail.com",
    "password": "Black" 
}

### Edit user by id
PUT http://localhost:3003/products/prod002

Content-Type: application/json

{
    "id": "prod003",
    "name": "Msadr",
    "price" : 2520,
    "description" : "asd",
    "imageURL" : "hasdos/seed/Mou"
}
